SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT P
JOIN 
    FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE 
    O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY 
    P.PRODUCT_ID
HAVING 
    SUM(O.AMOUNT) > 0
ORDER BY 
    TOTAL_SALES DESC, P.PRODUCT_ID;