-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_DATA_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT D.ID, D.PARENT_ID, GD.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA AS D
    INNER JOIN ECOLI_DATA_GENERATION AS GD
    ON GD.ID = D.PARENT_ID
), ECOLI_DATA_GENERATION_CHILD AS (
    SELECT P.ID, P.PARENT_ID, P.GENERATION, C.ID AS CHILD
    FROM ECOLI_DATA_GENERATION AS P
    LEFT JOIN ECOLI_DATA_GENERATION AS C
    ON P.ID = C.PARENT_ID
)

SELECT COUNT(*) AS COUNT ,GENERATION
FROM ECOLI_DATA_GENERATION_CHILD
WHERE CHILD IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC
