-- 코드를 입력하세요
SELECT AP.APNT_NO, AP.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM DOCTOR AS D,
(SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, A.MDDR_ID, A.APNT_YMD
FROM PATIENT AS P,
(SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
FROM APPOINTMENT
WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS') AS A
WHERE P.PT_NO = A.PT_NO) AS AP
WHERE AP.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC;