-- 코드를 입력하세요
WITH yearmonthuserid AS(
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM yearmonthuserid
ORDER BY YEAR ASC, MONTH ASC;