-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BII.CATEGORY, BII.TOTAL_SALES
FROM AUTHOR AS A,
(SELECT BI.CATEGORY, BI.AUTHOR_ID, SUM(BI.TOTAL_SALES) AS TOTAL_SALES
FROM
(SELECT B.CATEGORY, B.AUTHOR_ID, B.PRICE*BS.SALES AS TOTAL_SALES
FROM BOOK AS B, 
(SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID) AS BS
WHERE B.BOOK_ID = BS.BOOK_ID) AS BI
GROUP BY BI.AUTHOR_ID, BI.CATEGORY) AS BII
WHERE A.AUTHOR_ID = BII.AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
