-- 코드를 입력하세요
WITH AMOUNT_RECORD AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
), BEST_AMOUNT_RECORD AS (
    SELECT MEMBER_ID
    FROM AMOUNT_RECORD
    WHERE CNT = (SELECT MAX(CNT) FROM AMOUNT_RECORD)
), BEST_MEMBER_INFO AS (
    SELECT mp.MEMBER_NAME, mp.MEMBER_ID
    FROM MEMBER_PROFILE AS mp
    JOIN BEST_AMOUNT_RECORD AS bar
    ON mp.MEMBER_ID = bar.MEMBER_ID
)

SELECT bmi.MEMBER_NAME, rr.REVIEW_TEXT, DATE_FORMAT(rr.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as rr
JOIN BEST_MEMBER_INFO AS bmi
ON rr.MEMBER_ID = bmi.MEMBER_ID
ORDER BY REVIEW_DATE ASC , REVIEW_TEXT ASC;