-- 코드를 입력하세요
SELECT T2.CART_ID
FROM
(SELECT T1.CART_ID, COUNT(*) AS CNT
FROM
(SELECT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME IN ("MILK","YOGURT")
GROUP BY CART_ID, NAME) AS T1
GROUP BY CART_ID) AS T2
WHERE CNT = 2;