-- 코드를 작성해주세요
WITH FRONT_SKILL AS (
    SELECT NAME, CATEGORY, CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D, FRONT_SKILL AS F
WHERE D.SKILL_CODE & F.CODE !=0
ORDER BY ID ASC;

