WITH SALES AS (
    SELECT ONLINE_SALE_ID AS ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE, USER_ID FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID AS ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE, NULL AS USER_ID FROM OFFLINE_SALE
)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC