WITH RD AS (
    SELECT 
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        START_DATE,
        END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
DR AS (
    SELECT 
        CAR_ID,
        HISTORY_ID,
        DURATION,
        CASE 
            WHEN DURATION >= 90 THEN '90일 이상'
            WHEN DURATION >= 30 THEN '30일 이상'
            WHEN DURATION >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM RD
)
SELECT 
    R.HISTORY_ID,
    CAST(
        CASE 
            WHEN D.DURATION_TYPE IS NULL THEN C.DAILY_FEE * R.DURATION
            ELSE C.DAILY_FEE * R.DURATION * (100 - P.DISCOUNT_RATE) / 100
        END 
    AS SIGNED) AS FEE
FROM 
    RD R
JOIN CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID
LEFT JOIN DR D ON R.HISTORY_ID = D.HISTORY_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE AND D.DURATION_TYPE = P.DURATION_TYPE
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    R.HISTORY_ID DESC