WITH TRUCK AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
DISCOUNT AS (
    SELECT 
        CASE 
            WHEN DURATION_TYPE = '90일 이상' THEN 90
            WHEN DURATION_TYPE = '30일 이상' THEN 30
            WHEN DURATION_TYPE = '7일 이상' THEN 7
            ELSE 0
        END AS DURATION_TYPE, 
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    UNION
    SELECT 0 AS DURATION_TYPE, 0 AS DISCOUNT_RATE
),
HISTORY AS (
    SELECT 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY.HISTORY_ID, 
        TRUCK.DAILY_FEE, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS DATE,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN 90
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN 30
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN 7
            ELSE 0
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    JOIN TRUCK
    ON TRUCK.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
)
SELECT 
    HISTORY_ID, 
    ROUND(DAILY_FEE * DATE * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM HISTORY
JOIN DISCOUNT
ON HISTORY.DURATION_TYPE = DISCOUNT.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;
