-- 코드를 입력하세요
WITH TIME AS 
(
SELECT 0 AS HOUR , 0 AS COUNT
UNION
SELECT 1 AS HOUR , 0 AS COUNT
UNION
SELECT 2 AS HOUR , 0 AS COUNT
UNION
SELECT 3 AS HOUR , 0 AS COUNT
UNION
SELECT 4 AS HOUR , 0 AS COUNT
UNION
SELECT 5 AS HOUR , 0 AS COUNT
UNION
SELECT 6 AS HOUR , 0 AS COUNT
UNION
SELECT 7 AS HOUR , 0 AS COUNT
UNION
SELECT 8 AS HOUR , 0 AS COUNT
UNION
SELECT 9 AS HOUR , 0 AS COUNT
UNION
SELECT 10 AS HOUR , 0 AS COUNT
UNION
SELECT 11 AS HOUR , 0 AS COUNT
UNION
SELECT 12 AS HOUR , 0 AS COUNT
UNION
SELECT 13 AS HOUR , 0 AS COUNT
UNION
SELECT 14 AS HOUR , 0 AS COUNT
UNION
SELECT 15 AS HOUR , 0 AS COUNT
UNION
SELECT 16 AS HOUR , 0 AS COUNT
UNION
SELECT 17 AS HOUR , 0 AS COUNT
UNION
SELECT 18 AS HOUR , 0 AS COUNT
UNION
SELECT 19 AS HOUR , 0 AS COUNT
UNION
SELECT 20 AS HOUR , 0 AS COUNT
UNION
SELECT 21 AS HOUR , 0 AS COUNT
UNION
SELECT 22 AS HOUR , 0 AS COUNT
UNION
SELECT 23 AS HOUR , 0 AS COUNT
)
# WITH ANIMAL AS
# (
#     SELECT SUBSTRING(DATETIME,12,2) AS HOUR, COUNT(*) AS COUNT
#     FROM ANIMAL_OUTS
#     GROUP BY HOUR
# )

# SELECT *
# FROM ANIMAL;

SELECT T.HOUR, IFNULL( A.COUNT,0) AS COUNT
FROM TIME AS T
LEFT JOIN (SELECT SUBSTRING(DATETIME,12,2) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR) AS A
ON T.HOUR = A.HOUR
