-- 코드를 작성해주세요
WITH SCORE AS (
SELECT EMP_NO, SUM(SCORE)/2 AS SCORE
FROM HR_GRADE 
GROUP BY EMP_NO
),
GRADE AS (
SELECT EMP_NO, 
    CASE 
        WHEN SCORE >= 96 THEN "S"
        WHEN SCORE >= 90 THEN "A"
        WHEN SCORE >= 80 THEN "B"
    ELSE "C" END AS GRADE
FROM SCORE
),
SALARY AS (
SELECT E.EMP_NO, E.EMP_NAME, G.GRADE, E.SAL
FROM HR_EMPLOYEES AS E
LEFT JOIN GRADE AS G
ON E.EMP_NO = G.EMP_NO
) 
SELECT EMP_NO, EMP_NAME, GRADE, 
    CASE
        WHEN GRADE = "S" THEN (SAL/100)*20
        WHEN GRADE = "A" THEN (SAL/100)*15
        WHEN GRADE = "B" THEN (SAL/100)*10
    ELSE 0 END AS BONUS
FROM SALARY
ORDER BY EMP_NO ASC;